# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


PropertyEquipment.destroy_all
Publication.destroy_all
Category.destroy_all
Type.destroy_all
Equipment.destroy_all
Commune.destroy_all
Region.destroy_all

# Category
Category.create([{name: 'Arrendar'}, {name: 'Vender'}])

# Type
Type.create([{name: 'Casa'}, {name: 'Cabaña'}, {name: 'Departamento'}, {name: 'Oficina'}, {name: 'Terreno'}])

# Equipment - All
#Equipment.create([{name: 'Terraza'}, {name: 'Quincho'}, {name: 'Cocina Americana'}, {name: 'Bodega'}, {name: 'Piscina'}, 
#  {name: 'Aire Acondicionado'}, {name: 'Gimnasio'}, {name: 'Calefacción'}])


Equipment.create([{name: 'Baño Visitas'}, {name: 'Servicios'}, {name: 'Terraza'}, {name: 'Logia'}, {name: 'Cocina Amoblada'}, 
  {name: 'Cocina Americana'}, {name: 'Gimnasio'}, {name: 'Calefacción'}, {name: 'Bodega'}, {name: 'Aire Acondicionado'}, {name: 'Conserjería'}])


 
# Departmento#

#Espacios#

# Baño visitas
# Servicios
# Terraza
# Logia
#Cocina#

# Despensa
# Cocina amoblada
# Comedor de diario
#Otros#

# Bodega
# Piscina
# Gimnasio
# Aire acondicionado
# Calefacción
# Conserjería#
#

#Casa #

#Espacios#

# Baño visitas
# Servicios
# Patio trasero
# Antejardín
# Logia
#Cocina#

# Despensa
# Cocina amoblada
# Comedor de diario
#Otros#

# Bodega
# Piscina
# Aire acondicionado
# Calefacción
# Riego automático#
#
#

#Oficina
# 
#Espacios#

# Sala de reuniones
# Cocina
# Recepción
# Planta libre
#Otros#

# Aire acondicionado
# Calefacción
# Jardín



# Region
Region.create(name: "Región Metropolitana")
Region.create(name: "Región de Arica y Parinacota")
Region.create(name: "Región de Tarapacá")
Region.create(name: "Región de Antofagasta")
Region.create(name: "Región de Atacama")
Region.create(name: "Región de Coquimbo")
Region.create(name: "Región de Valparaiso")
Region.create(name: "Región del Libertador General Bernardo O'Higgins")
Region.create(name: "Región del Maule")
Region.create(name: "Región del Biobío")
Region.create(name: "Región de la Araucanía")
Region.create(name: "Región de los Ríos")
Region.create(name: "Región de los Lagos")
Region.create(name: "Región de Aysén del General Carlos Ibáñez del Campo")
Region.create(name: "Región de Magallanes y de la Antártica Chilena")

# Commune
Commune.create(name: "Arica", province: "Arica", region: Region.find_by(name: "Región de Arica y Parinacota"))
Commune.create(name: "Camarones", province: "Arica", region: Region.find_by(name: "Región de Arica y Parinacota"))
Commune.create(name: "Putre", province: "Parinacota", region: Region.find_by(name: "Región de Arica y Parinacota"))
Commune.create(name: "General Lagos", province: "Parinacota", region: Region.find_by(name: "Región de Arica y Parinacota"))
Commune.create(name: "Iquique", province: "Iquique", region: Region.find_by(name: "Región de Tarapacá"))
Commune.create(name: "Alto Hospicio", province: "Iquique", region: Region.find_by(name: "Región de Tarapacá"))
Commune.create(name: "Pozo Almonte", province: "Tamarugal", region: Region.find_by(name: "Región de Tarapacá"))
Commune.create(name: "Camiña", province: "Tamarugal", region: Region.find_by(name: "Región de Tarapacá"))
Commune.create(name: "Colchane", province: "Tamarugal", region: Region.find_by(name: "Región de Tarapacá"))
Commune.create(name: "Huara", province: "Tamarugal", region: Region.find_by(name: "Región de Tarapacá"))
Commune.create(name: "Pica", province: "Tamarugal", region: Region.find_by(name: "Región de Tarapacá"))
Commune.create(name: "Antofagasta", province: "Antofagasta", region: Region.find_by(name: "Región de Antofagasta"))
Commune.create(name: "Mejillones", province: "Antofagasta", region: Region.find_by(name: "Región de Antofagasta"))
Commune.create(name: "Sierra Gorda", province:   "Antofagasta", region: Region.find_by(name: "Región de Antofagasta"))
Commune.create(name: "Taltal", province: "Antofagasta", region: Region.find_by(name: "Región de Antofagasta"))
Commune.create(name: "Calama", province: "El Loa", region: Region.find_by(name: "Región de Antofagasta"))
Commune.create(name: "Ollagüe", province: "El Loa", region: Region.find_by(name: "Región de Antofagasta"))
Commune.create(name: "San Pedro de Atacama", province: "El Loa", region: Region.find_by(name: "Región de Antofagasta"))
Commune.create(name: "Tocopilla", province: "Tocopilla", region: Region.find_by(name: "Región de Antofagasta"))
Commune.create(name: "María Elena", province: "Tocopilla", region: Region.find_by(name: "Región de Antofagasta"))
Commune.create(name: "Copiapó", province: "Copiapó", region: Region.find_by(name: "Región de Atacama"))
Commune.create(name: "Caldera", province: "Copiapó", region: Region.find_by(name: "Región de Atacama"))
Commune.create(name: "Tierra Amarilla", province: "Copiapó", region: Region.find_by(name: "Región de Atacama"))
Commune.create(name: "Chañaral", province: "Chañaral", region: Region.find_by(name: "Región de Atacama"))
Commune.create(name: "Diego de Almagro", province: "Chañaral", region: Region.find_by(name: "Región de Atacama"))
Commune.create(name: "Vallenar", province: "Huasco", region: Region.find_by(name: "Región de Atacama"))
Commune.create(name: "Alto del Carmen", province: "Huasco", region: Region.find_by(name: "Región de Atacama"))
Commune.create(name: "Freirina", province: "Huasco", region: Region.find_by(name: "Región de Atacama"))
Commune.create(name: "Huasco", province: "Huasco", region: Region.find_by(name: "Región de Atacama"))
Commune.create(name: "La Serena", province: "Elqui", region: Region.find_by(name: "Región de Coquimbo"))
Commune.create(name: "Coquimbo", province: "Elqui", region: Region.find_by(name: "Región de Coquimbo"))
Commune.create(name: "Andacollo", province: "Elqui", region: Region.find_by(name: "Región de Coquimbo"))
Commune.create(name: "La Higuera", province: "Elqui", region: Region.find_by(name: "Región de Coquimbo"))
Commune.create(name: "Paiguano", province: "Elqui", region: Region.find_by(name: "Región de Coquimbo"))
Commune.create(name: "Vicuña", province: "Elqui", region: Region.find_by(name: "Región de Coquimbo"))
Commune.create(name: "Illapel", province: "Choapa", region: Region.find_by(name: "Región de Coquimbo"))
Commune.create(name: "Canela", province: "Choapa", region: Region.find_by(name: "Región de Coquimbo"))
Commune.create(name: "Los Vilos", province: "Choapa", region: Region.find_by(name: "Región de Coquimbo"))
Commune.create(name: "Salamanca", province: "Choapa", region: Region.find_by(name: "Región de Coquimbo"))
Commune.create(name: "Ovalle", province: "Limarí", region: Region.find_by(name: "Región de Coquimbo"))
Commune.create(name: "Combarbalá", province: "Limarí", region: Region.find_by(name: "Región de Coquimbo"))
Commune.create(name: "Monte Patria", province: "Limarí", region: Region.find_by(name: "Región de Coquimbo"))
Commune.create(name: "Punitaqui", province: "Limarí", region: Region.find_by(name: "Región de Coquimbo"))
Commune.create(name: "Río Hurtado", province: "Limarí", region: Region.find_by(name: "Región de Coquimbo",))
Commune.create(name: "Valparaiso", province: "Valparaiso", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Casablanca", province: "Valparaiso", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Concón", province: "Valparaiso", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Juan Fernández", province: "Valparaiso", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Puchuncaví", province: "Valparaiso", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Quintero", province: "Valparaiso", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Viña del Mar", province: "Valparaiso", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Isla de Pascua", province: "Isla de Pascua", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Los Andes", province: "Los Andes", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Calle Larga", province: "Los Andes", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Riconada", province: "Los Andes", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "San Esteban", province: "Los Andes", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "La Ligua", province: "Petorca", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Cabildo", province: "Petorca", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Papudo", province: "Petorca", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Petorca", province: "Petorca", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Zapallar", province: "Petorca", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Quillota", province: "Quillota", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Calera", province: "Quillota", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Hijuelas", province: "Quillota", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "La Cruz", province: "Quillota", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Nogales", province: "Quillota", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "San Antonio", province: "San Antonio", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Algarrobo", province: "San Antonio", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Cartagena", province: "San Antonio", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "El Quisco", province: "San Antonio", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "El Tabo", province: "San Antonio", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Santo Domingo", province: "San Antonio", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "San Felipe", province: "San Felipe de Aconcagua", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Catemu", province: "San Felipe de Aconcagua", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Llaillay", province: "San Felipe de Aconcagua", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Panquehue", province: "San Felipe de Aconcagua", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Putaendo", province: "San Felipe de Aconcagua", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Santa María", province: "San Felipe de Aconcagua", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Quilpué", province: "Marga Marga", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Limache", province: "Marga Marga", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Olmué", province: "Marga Marga", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Villa Alemana", province: "Marga Marga", region: Region.find_by(name: "Región de Valparaiso"))
Commune.create(name: "Rancagua", province: "Cachapoal", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Codegua", province: "Cachapoal", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Coinco", province: "Cachapoal", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Coltauco", province: "Cachapoal", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Doñihue", province: "Cachapoal", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Graneros", province: "Cachapoal", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Las Cabras", province: "Cachapoal", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Machalí", province: "Cachapoal", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Malloa", province: "Cachapoal", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Mostazal", province: "Cachapoal", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Olivar", province: "Cachapoal", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Peumo", province: "Cachapoal", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Pichidegua", province: "Cachapoal", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Quinta de Tilcoco", province: "Cachapoal", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Rengo", province: "Cachapoal", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Requínoa", province: "Cachapoal", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "San Vicente", province: "Cachapoal", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Pichilemu", province: "Cardenal Caro", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "La Estrella", province: "Cardenal Caro", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Litueche", province: "Cardenal Caro", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Marichihue", province: "Cardenal Caro", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Navidad", province: "Cardenal Caro", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Paredones", province: "Cardenal Caro", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "San Fernando", province: "Colchagua", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Chépica", province: "Colchagua", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Chimbarongo", province: "Colchagua", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Lolol", province: "Colchagua", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Nancagua", province: "Colchagua", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Palmilla", province: "Colchagua", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Peralillo", province: "Colchagua", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Placilla", province: "Colchagua", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Pumanque", province: "Colchagua", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Santa Cruz", province: "Colchagua", region: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins"))
Commune.create(name: "Talca", province: "Talca", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Constitución", province: "Talca", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Curepto", province: "Talca", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Empedrado", province: "Talca", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Maule", province: "Talca", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Pelarco", province: "Talca", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Pencahue", province: "Talca", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Río Claro", province: "Talca", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "San Clemente", province: "Talca", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "San Rafael", province: "Talca", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Cauquenes", province: "Cauquenes", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Chanco", province: "Cauquenes", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Pelluhue", province: "Cauquenes", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Curicó", province: "Curicó", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Hualañé", province: "Curicó", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Licantén", province: "Curicó", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Molina", province: "Curicó", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Rauco", province: "Curicó", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Romeral", province: "Curicó", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Sagrada Familia", province: "Curicó", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Teno", province: "Curicó", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Vichuquén", province: "Curicó", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Linares", province: "Linares", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Colbún", province: "Linares", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Longaví", province: "Linares", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Parral", province: "Linares", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Retiro", province: "Linares", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "San Javier", province: "Linares", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Villa Alegre", province: "Linares", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Yerbas Buenas", province: "Linares", region: Region.find_by(name: "Región del Maule"))
Commune.create(name: "Concepción", province: "Concepción", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Coronel", province: "Concepción", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Chiguayante", province: "Concepción", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Florida", province: "Concepción", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Hualqui", province: "Concepción", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Lota", province: "Concepción", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Penco", province: "Concepción", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "San Pedro de la Paz", province: "Concepción", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Santa Juana", province: "Concepción", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Talcahuano", province: "Concepción", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Tomé", province: "Concepción", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Hualpén", province: "Concepción", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Lebu", province: "Arauco", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Arauco", province: "Arauco", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Cañete", province: "Arauco", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Contulmo", province: "Arauco", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Curanilahue", province: "Arauco", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Los Álamos", province: "Arauco", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Tirúa", province: "Arauco", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Los Ángeles", province: "Biobío", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Antuco", province: "Biobío", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Cabrero", province: "Biobío", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Laja", province: "Biobío", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Mulchén", province: "Biobío", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Nacimiento", province: "Biobío", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Negrete", province: "Biobío", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Quilaco", province: "Biobío", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Quilleco", province: "Biobío", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "San Rosendo", province: "Biobío", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Santa Bárbara", province: "Biobío", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Tucapel", province: "Biobío", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Yumbel", province: "Biobío", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Alto Biobío", province: "Biobío", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Chillán", province: "Ñuble", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Bulnes", province: "Ñuble", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Cobquecura", province: "Ñuble", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Coelemu", province: "Ñuble", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Coihueco", province: "Ñuble", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Chillán Viejo", province: "Ñuble", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "El Carmen", province: "Ñuble", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Ninhue", province: "Ñuble", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Ñiquén", province: "Ñuble", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Pemuco", province: "Ñuble", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Pinto", province: "Ñuble", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Portezuelo", province: "Ñuble", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Quillón", province: "Ñuble", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Quirihue", province: "Ñuble", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Ránquil", province: "Ñuble", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "San Carlos", province: "Ñuble", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "San Fabián", province: "Ñuble", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "San Ignacio", province: "Ñuble", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "San Nicolás", province: "Ñuble", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Treguaco", province: "Ñuble", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Yungay", province: "Ñuble", region: Region.find_by(name: "Región del Biobío"))
Commune.create(name: "Temuco", province: "Cautín", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Carahu", province: "Cautín", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Cunco", province: "Cautín", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Curarrehue", province: "Cautín", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Freire", province: "Cautín", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Galvarin", province: "Cautín", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Gorbea", province: "Cautín", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Lautaro", province: "Cautín", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Loncoche", province: "Cautín", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Melipeuco", province: "Cautín", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Nueva Imperial", province: "Cautín", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Padre las Casa", province: "Cautín", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Perquenco", province: "Cautín", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Pitrufquén", province: "Cautín", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Pucó", province: "Cautín", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Saavedra", province: "Cautín", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Teodoro Schmid", province: "Cautín", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Toltén", province: "Cautín", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Vilcún", province: "Cautín", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Villarrica", province: "Cautín", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Cholchol", province: "Cautín", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Angol", province: "Malleco", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Collipulli", province: "Malleco", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Curacautín", province: "Malleco", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Ercilla", province: "Malleco", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Lonquimay", province: "Malleco", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Los Sauces", province: "Malleco", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Lumaco", province: "Malleco", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Purén", province: "Malleco", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Renaico", province: "Malleco", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Traiguén", province: "Malleco", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Victoria", province: "Malleco", region: Region.find_by(name: "Región de la Araucanía"))
Commune.create(name: "Valdivia", province: "Valdivia", region: Region.find_by(name: "Región de los Ríos"))
Commune.create(name: "Corral", province: "Valdivia", region: Region.find_by(name: "Región de los Ríos"))
Commune.create(name: "Lanco", province: "Valdivia", region: Region.find_by(name: "Región de los Ríos"))
Commune.create(name: "Los Lagos", province: "Valdivia", region: Region.find_by(name: "Región de los Ríos"))
Commune.create(name: "Máfil", province: "Valdivia", region: Region.find_by(name: "Región de los Ríos"))
Commune.create(name: "Mariquina", province: "Valdivia", region: Region.find_by(name: "Región de los Ríos"))
Commune.create(name: "Paillaco", province: "Valdivia", region: Region.find_by(name: "Región de los Ríos"))
Commune.create(name: "Panguipulli", province: "Valdivia", region: Region.find_by(name: "Región de los Ríos"))
Commune.create(name: "La Unión", province: "Ranco", region: Region.find_by(name: "Región de los Ríos"))
Commune.create(name: "Futrono", province: "Ranco", region: Region.find_by(name: "Región de los Ríos"))
Commune.create(name: "Lago Ranco", province: "Ranco", region: Region.find_by(name: "Región de los Ríos"))
Commune.create(name: "Río Bueno", province: "Ranco", region: Region.find_by(name: "Región de los Ríos", ))
Commune.create(name: "Puerto Montt", province: "Llanquihue", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Calbuco", province: "Llanquihue", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Cochamó", province: "Llanquihue", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Fresia", province: "Llanquihue", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Frutillar", province: "Llanquihue", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Los Muermos", province: "Llanquihue", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Llanquihue", province: "Llanquihue", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Maullín", province: "Llanquihue", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Puerto Varas", province: "Llanquihue", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Castro", province: "Chiloé", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Ancud", province: "Chiloé", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Chonchi", province: "Chiloé", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Curaco de Vélez", province: "Chiloé", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Dalcahue", province: "Chiloé", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Puqueldón", province: "Chiloé", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Queilén", province: "Chiloé", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Quellón", province: "Chiloé", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Quemchi", province: "Chiloé", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Quinchao", province: "Chiloé", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Osorno", province: "Osorno", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Puerto Octay", province: "Osorno", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Purranque", province: "Osorno", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Puyehue", province: "Osorno", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Río Negro", province: "Osorno", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "San Juan de la Costa", province: "Osorno", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "San Pablo", province: "Osorno", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Chaitén", province: "Palena", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Futaleufú", province: "Palena", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Hualaihué", province: "Palena", region: Region.find_by(name: "Región de los Lagos"))
Commune.create(name: "Coyhaique", province: "Coyhaique", region: Region.find_by(name: "Región de Aysén del General Carlos Ibáñez del Campo"))
Commune.create(name: "Lago Verde", province: "Coyhaique", region: Region.find_by(name: "Región de Aysén del General Carlos Ibáñez del Campo"))
Commune.create(name: "Aisén", province: "Aisén", region: Region.find_by(name: "Región de Aysén del General Carlos Ibáñez del Campo"))
Commune.create(name: "Cisnes", province: "Aisén", region: Region.find_by(name: "Región de Aysén del General Carlos Ibáñez del Campo"))
Commune.create(name: "Guaitecas", province: "Aisén", region: Region.find_by(name: "Región de Aysén del General Carlos Ibáñez del Campo"))
Commune.create(name: "Cochrane", province: "Capitán Pratt", region: Region.find_by(name: "Región de Aysén del General Carlos Ibáñez del Campo"))
Commune.create(name: "O’Higgins", province: "Capitán Pratt", region: Region.find_by(name: "Región de Aysén del General Carlos Ibáñez del Campo"))
Commune.create(name: "Tortel", province: "Capitán Pratt", region: Region.find_by(name: "Región de Aysén del General Carlos Ibáñez del Campo"))
Commune.create(name: "Chile Chico", province: "General Carrera", region: Region.find_by(name: "Región de Aysén del General Carlos Ibáñez del Campo"))
Commune.create(name: "Río Ibáñez", province: "General Carrera", region: Region.find_by(name: "Región de Aysén del General Carlos Ibáñez del Campo"))
Commune.create(name: "Punta Arenas", province: "Magallanes", region: Region.find_by(name: "Región de Magallanes y de la Antártica Chilena"))
Commune.create(name: "Laguna Blanca", province: "Magallanes", region: Region.find_by(name: "Región de Magallanes y de la Antártica Chilena"))
Commune.create(name: "Río Verde", province: "Magallanes", region: Region.find_by(name: "Región de Magallanes y de la Antártica Chilena"))
Commune.create(name: "San Gregorio", province: "Magallanes", region: Region.find_by(name: "Región de Magallanes y de la Antártica Chilena"))
Commune.create(name: "Cabo de Hornos", province: "Antártica Chilena", region: Region.find_by(name: "Región de Magallanes y de la Antártica Chilena"))
Commune.create(name: "Antártica", province: "Antártica Chilena", region: Region.find_by(name: "Región de Magallanes y de la Antártica Chilena"))
Commune.create(name: "Porvenir", province: "Tierra del Fuego", region: Region.find_by(name: "Región de Magallanes y de la Antártica Chilena"))
Commune.create(name: "Primavera", province: "Tierra del Fuego", region: Region.find_by(name: "Región de Magallanes y de la Antártica Chilena"))
Commune.create(name: "Timaukel", province: "Tierra del Fuego", region: Region.find_by(name: "Región de Magallanes y de la Antártica Chilena"))
Commune.create(name: "Natales", province: "Última Esperanza", region: Region.find_by(name: "Región de Magallanes y de la Antártica Chilena"))
Commune.create(name: "Torres del Paine", province: "Última Esperanza", region: Region.find_by(name: "Región de Magallanes y de la Antártica Chilena"))
Commune.create(name: "Santiago", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Cerrillos", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Cerro Navia", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Conchalí", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "El Bosque", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Estación Central", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Huechuraba", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Independencia", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "La Cisterna", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "La Florida", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "La Granja", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "La Pintana", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "La Reina", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Las Condes", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Lo Barnechea", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Lo Espejo", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Lo Prado", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Macul", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Maipú", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Ñuñoa", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Pedro Aguirre Cerda", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Peñalolén", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Providencia", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Pudahuel", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Quilicura", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Quinta Normal", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Recoleta", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Renca", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "San Joaquín", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "San Miguel", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "San Ramón", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Vitacura", province: "Santiago", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Puente Alto", province: "Cordillera", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Pirque", province: "Cordillera", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "San José de Maipo", province: "Cordillera", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Colina", province: "Chacabuco", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Lampa", province: "Chacabuco", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Tiltil", province: "Chacabuco", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "San Bernardo", province: "Maipo", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Buin", province: "Maipo", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Calera de Tango", province: "Maipo", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Paine", province: "Maipo", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Melipilla", province: "Mellipilla", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Alhué", province: "Mellipilla", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Curacaví", province: "Mellipilla", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "María Pinto", province: "Mellipilla", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "San Pedro", province: "Mellipilla", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Talagante", province: "Talagante", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "El Monte", province: "Talagante", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Isla de Maipo", province: "Talagante", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Padre Hurtado", province: "Talagante", region: Region.find_by(name: "Región Metropolitana"))
Commune.create(name: "Peñaflor", province: "Talagante", region: Region.find_by(name: "Región Metropolitana"))
















#Commune.create(name: "Arica", province: "Arica", region_id: Region.find_by(name: "Región de Arica y Parinacota").id)
#Commune.create(name: "Camarones", province: "Arica", region_id: Region.find_by(name: "Región de Arica y Parinacota").id)
#Commune.create(name: "Putre", province: "Parinacota", region_id: Region.find_by(name: "Región de Arica y Parinacota").id)
#Commune.create(name: "General Lagos", province: "Parinacota", region_id: Region.find_by(name: "Región de Arica y Parinacota").id)
#Commune.create(name: "Iquique", province: "Iquique", region_id: Region.find_by(name: "Región de Tarapacá").id)
#Commune.create(name: "Alto Hospicio", province: "Iquique", region_id: Region.find_by(name: "Región de Tarapacá").id)
#Commune.create(name: "Pozo Almonte", province: "Tamarugal", region_id: Region.find_by(name: "Región de Tarapacá").id)
#Commune.create(name: "Camiña", province: "Tamarugal", region_id: Region.find_by(name: "Región de Tarapacá").id)
#Commune.create(name: "Colchane", province: "Tamarugal", region_id: Region.find_by(name: "Región de Tarapacá").id)
#Commune.create(name: "Huara", province: "Tamarugal", region_id: Region.find_by(name: "Región de Tarapacá").id)
#Commune.create(name: "Pica", province: "Tamarugal", region_id: Region.find_by(name: "Región de Tarapacá").id)
#Commune.create(name: "Antofagasta", province: "Antofagasta", region_id: Region.find_by(name: "Región de Antofagasta").id)
#Commune.create(name: "Mejillones", province: "Antofagasta", region_id: Region.find_by(name: "Región de Antofagasta").id)
#Commune.create(name: "Sierra Gorda", province:   "Antofagasta", region_id: Region.find_by(name: "Región de Antofagasta").id)
#Commune.create(name: "Taltal", province: "Antofagasta", region_id: Region.find_by(name: "Región de Antofagasta").id)
#Commune.create(name: "Calama", province: "El Loa", region_id: Region.find_by(name: "Región de Antofagasta").id)
#Commune.create(name: "Ollagüe", province: "El Loa", region_id: Region.find_by(name: "Región de Antofagasta").id)
#Commune.create(name: "San Pedro de Atacama", province: "El Loa", region_id: Region.find_by(name: "Región de Antofagasta").id)
#Commune.create(name: "Tocopilla", province: "Tocopilla", region_id: Region.find_by(name: "Región de Antofagasta").id)
#Commune.create(name: "María Elena", province: "Tocopilla", region_id: Region.find_by(name: "Región de Antofagasta").id)
#Commune.create(name: "Copiapó", province: "Copiapó", region_id: Region.find_by(name: "Región de Atacama").id)
#Commune.create(name: "Caldera", province: "Copiapó", region_id: Region.find_by(name: "Región de Atacama").id)
#Commune.create(name: "Tierra Amarilla", province: "Copiapó", region_id: Region.find_by(name: "Región de Atacama").id)
#Commune.create(name: "Chañaral", province: "Chañaral", region_id: Region.find_by(name: "Región de Atacama").id)
#Commune.create(name: "Diego de Almagro", province: "Chañaral", region_id: Region.find_by(name: "Región de Atacama").id)
#Commune.create(name: "Vallenar", province: "Huasco", region_id: Region.find_by(name: "Región de Atacama").id)
#Commune.create(name: "Alto del Carmen", province: "Huasco", region_id: Region.find_by(name: "Región de Atacama").id)
#Commune.create(name: "Freirina", province: "Huasco", region_id: Region.find_by(name: "Región de Atacama").id)
#Commune.create(name: "Huasco", province: "Huasco", region_id: Region.find_by(name: "Región de Atacama").id)
#Commune.create(name: "La Serena", province: "Elqui", region_id: Region.find_by(name: "Región de Coquimbo").id)
#Commune.create(name: "Coquimbo", province: "Elqui", region_id: Region.find_by(name: "Región de Coquimbo").id)
#Commune.create(name: "Andacollo", province: "Elqui", region_id: Region.find_by(name: "Región de Coquimbo").id)
#Commune.create(name: "La Higuera", province: "Elqui", region_id: Region.find_by(name: "Región de Coquimbo").id)
#Commune.create(name: "Paiguano", province: "Elqui", region_id: Region.find_by(name: "Región de Coquimbo").id)
#Commune.create(name: "Vicuña", province: "Elqui", region_id: Region.find_by(name: "Región de Coquimbo").id)
#Commune.create(name: "Illapel", province: "Choapa", region_id: Region.find_by(name: "Región de Coquimbo").id)
#Commune.create(name: "Canela", province: "Choapa", region_id: Region.find_by(name: "Región de Coquimbo").id)
#Commune.create(name: "Los Vilos", province: "Choapa", region_id: Region.find_by(name: "Región de Coquimbo").id)
#Commune.create(name: "Salamanca", province: "Choapa", region_id: Region.find_by(name: "Región de Coquimbo").id)
#Commune.create(name: "Ovalle", province: "Limarí", region_id: Region.find_by(name: "Región de Coquimbo").id)
#Commune.create(name: "Combarbalá", province: "Limarí", region_id: Region.find_by(name: "Región de Coquimbo").id)
#Commune.create(name: "Monte Patria", province: "Limarí", region_id: Region.find_by(name: "Región de Coquimbo").id)
#Commune.create(name: "Punitaqui", province: "Limarí", region_id: Region.find_by(name: "Región de Coquimbo").id)
#Commune.create(name: "Río Hurtado", province: "Limarí", region_id: Region.find_by(name: "Región de Coquimbo",).id)
#Commune.create(name: "Valparaiso", province: "Valparaiso", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Casablanca", province: "Valparaiso", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Concón", province: "Valparaiso", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Juan Fernández", province: "Valparaiso", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Puchuncaví", province: "Valparaiso", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Quintero", province: "Valparaiso", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Viña del Mar", province: "Valparaiso", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Isla de Pascua", province: "Isla de Pascua", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Los Andes", province: "Los Andes", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Calle Larga", province: "Los Andes", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Riconada", province: "Los Andes", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "San Esteban", province: "Los Andes", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "La Ligua", province: "Petorca", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Cabildo", province: "Petorca", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Papudo", province: "Petorca", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Petorca", province: "Petorca", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Zapallar", province: "Petorca", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Quillota", province: "Quillota", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Calera", province: "Quillota", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Hijuelas", province: "Quillota", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "La Cruz", province: "Quillota", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Nogales", province: "Quillota", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "San Antonio", province: "San Antonio", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Algarrobo", province: "San Antonio", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Cartagena", province: "San Antonio", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "El Quisco", province: "San Antonio", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "El Tabo", province: "San Antonio", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Santo Domingo", province: "San Antonio", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "San Felipe", province: "San Felipe de Aconcagua", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Catemu", province: "San Felipe de Aconcagua", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Llaillay", province: "San Felipe de Aconcagua", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Panquehue", province: "San Felipe de Aconcagua", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Putaendo", province: "San Felipe de Aconcagua", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Santa María", province: "San Felipe de Aconcagua", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Quilpué", province: "Marga Marga", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Limache", province: "Marga Marga", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Olmué", province: "Marga Marga", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Villa Alemana", province: "Marga Marga", region_id: Region.find_by(name: "Región de Valparaiso").id)
#Commune.create(name: "Rancagua", province: "Cachapoal", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Codegua", province: "Cachapoal", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Coinco", province: "Cachapoal", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Coltauco", province: "Cachapoal", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Doñihue", province: "Cachapoal", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Graneros", province: "Cachapoal", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Las Cabras", province: "Cachapoal", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Machalí", province: "Cachapoal", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Malloa", province: "Cachapoal", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Mostazal", province: "Cachapoal", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Olivar", province: "Cachapoal", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Peumo", province: "Cachapoal", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Pichidegua", province: "Cachapoal", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Quinta de Tilcoco", province: "Cachapoal", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Rengo", province: "Cachapoal", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Requínoa", province: "Cachapoal", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "San Vicente", province: "Cachapoal", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Pichilemu", province: "Cardenal Caro", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "La Estrella", province: "Cardenal Caro", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Litueche", province: "Cardenal Caro", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Marichihue", province: "Cardenal Caro", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Navidad", province: "Cardenal Caro", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Paredones", province: "Cardenal Caro", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "San Fernando", province: "Colchagua", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Chépica", province: "Colchagua", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Chimbarongo", province: "Colchagua", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Lolol", province: "Colchagua", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Nancagua", province: "Colchagua", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Palmilla", province: "Colchagua", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Peralillo", province: "Colchagua", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Placilla", province: "Colchagua", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Pumanque", province: "Colchagua", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Santa Cruz", province: "Colchagua", region_id: Region.find_by(name: "Región del Libertador General Bernardo O'Higgins").id)
#Commune.create(name: "Talca", province: "Talca", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Constitución", province: "Talca", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Curepto", province: "Talca", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Empedrado", province: "Talca", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Maule", province: "Talca", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Pelarco", province: "Talca", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Pencahue", province: "Talca", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Río Claro", province: "Talca", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "San Clemente", province: "Talca", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "San Rafael", province: "Talca", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Cauquenes", province: "Cauquenes", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Chanco", province: "Cauquenes", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Pelluhue", province: "Cauquenes", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Curicó", province: "Curicó", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Hualañé", province: "Curicó", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Licantén", province: "Curicó", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Molina", province: "Curicó", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Rauco", province: "Curicó", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Romeral", province: "Curicó", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Sagrada Familia", province: "Curicó", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Teno", province: "Curicó", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Vichuquén", province: "Curicó", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Linares", province: "Linares", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Colbún", province: "Linares", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Longaví", province: "Linares", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Parral", province: "Linares", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Retiro", province: "Linares", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "San Javier", province: "Linares", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Villa Alegre", province: "Linares", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Yerbas Buenas", province: "Linares", region_id: Region.find_by(name: "Región del Maule").id)
#Commune.create(name: "Concepción", province: "Concepción", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Coronel", province: "Concepción", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Chiguayante", province: "Concepción", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Florida", province: "Concepción", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Hualqui", province: "Concepción", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Lota", province: "Concepción", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Penco", province: "Concepción", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "San Pedro de la Paz", province: "Concepción", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Santa Juana", province: "Concepción", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Talcahuano", province: "Concepción", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Tomé", province: "Concepción", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Hualpén", province: "Concepción", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Lebu", province: "Arauco", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Arauco", province: "Arauco", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Cañete", province: "Arauco", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Contulmo", province: "Arauco", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Curanilahue", province: "Arauco", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Los Álamos", province: "Arauco", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Tirúa", province: "Arauco", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Los Ángeles", province: "Biobío", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Antuco", province: "Biobío", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Cabrero", province: "Biobío", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Laja", province: "Biobío", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Mulchén", province: "Biobío", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Nacimiento", province: "Biobío", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Negrete", province: "Biobío", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Quilaco", province: "Biobío", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Quilleco", province: "Biobío", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "San Rosendo", province: "Biobío", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Santa Bárbara", province: "Biobío", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Tucapel", province: "Biobío", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Yumbel", province: "Biobío", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Alto Biobío", province: "Biobío", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Chillán", province: "Ñuble", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Bulnes", province: "Ñuble", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Cobquecura", province: "Ñuble", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Coelemu", province: "Ñuble", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Coihueco", province: "Ñuble", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Chillán Viejo", province: "Ñuble", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "El Carmen", province: "Ñuble", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Ninhue", province: "Ñuble", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Ñiquén", province: "Ñuble", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Pemuco", province: "Ñuble", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Pinto", province: "Ñuble", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Portezuelo", province: "Ñuble", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Quillón", province: "Ñuble", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Quirihue", province: "Ñuble", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Ránquil", province: "Ñuble", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "San Carlos", province: "Ñuble", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "San Fabián", province: "Ñuble", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "San Ignacio", province: "Ñuble", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "San Nicolás", province: "Ñuble", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Treguaco", province: "Ñuble", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Yungay", province: "Ñuble", region_id: Region.find_by(name: "Región del Biobío").id)
#Commune.create(name: "Temuco", province: "Cautín", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Carahu", province: "Cautín", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Cunco", province: "Cautín", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Curarrehue", province: "Cautín", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Freire", province: "Cautín", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Galvarin", province: "Cautín", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Gorbea", province: "Cautín", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Lautaro", province: "Cautín", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Loncoche", province: "Cautín", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Melipeuco", province: "Cautín", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Nueva Imperial", province: "Cautín", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Padre las Casa", province: "Cautín", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Perquenco", province: "Cautín", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Pitrufquén", province: "Cautín", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Pucó", province: "Cautín", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Saavedra", province: "Cautín", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Teodoro Schmid", province: "Cautín", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Toltén", province: "Cautín", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Vilcún", province: "Cautín", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Villarrica", province: "Cautín", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Cholchol", province: "Cautín", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Angol", province: "Malleco", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Collipulli", province: "Malleco", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Curacautín", province: "Malleco", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Ercilla", province: "Malleco", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Lonquimay", province: "Malleco", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Los Sauces", province: "Malleco", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Lumaco", province: "Malleco", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Purén", province: "Malleco", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Renaico", province: "Malleco", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Traiguén", province: "Malleco", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Victoria", province: "Malleco", region_id: Region.find_by(name: "Región de la Araucanía").id)
#Commune.create(name: "Valdivia", province: "Valdivia", region_id: Region.find_by(name: "Región de los Ríos").id)
#Commune.create(name: "Corral", province: "Valdivia", region_id: Region.find_by(name: "Región de los Ríos").id)
#Commune.create(name: "Lanco", province: "Valdivia", region_id: Region.find_by(name: "Región de los Ríos").id)
#Commune.create(name: "Los Lagos", province: "Valdivia", region_id: Region.find_by(name: "Región de los Ríos").id)
#Commune.create(name: "Máfil", province: "Valdivia", region_id: Region.find_by(name: "Región de los Ríos").id)
#Commune.create(name: "Mariquina", province: "Valdivia", region_id: Region.find_by(name: "Región de los Ríos").id)
#Commune.create(name: "Paillaco", province: "Valdivia", region_id: Region.find_by(name: "Región de los Ríos").id)
#Commune.create(name: "Panguipulli", province: "Valdivia", region_id: Region.find_by(name: "Región de los Ríos").id)
#Commune.create(name: "La Unión", province: "Ranco", region_id: Region.find_by(name: "Región de los Ríos").id)
#Commune.create(name: "Futrono", province: "Ranco", region_id: Region.find_by(name: "Región de los Ríos").id)
#Commune.create(name: "Lago Ranco", province: "Ranco", region_id: Region.find_by(name: "Región de los Ríos").id)
#Commune.create(name: "Río Bueno", province: "Ranco", region_id: Region.find_by(name: "Región de los Ríos", ).id)
#Commune.create(name: "Puerto Montt", province: "Llanquihue", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Calbuco", province: "Llanquihue", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Cochamó", province: "Llanquihue", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Fresia", province: "Llanquihue", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Frutillar", province: "Llanquihue", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Los Muermos", province: "Llanquihue", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Llanquihue", province: "Llanquihue", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Maullín", province: "Llanquihue", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Puerto Varas", province: "Llanquihue", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Castro", province: "Chiloé", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Ancud", province: "Chiloé", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Chonchi", province: "Chiloé", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Curaco de Vélez", province: "Chiloé", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Dalcahue", province: "Chiloé", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Puqueldón", province: "Chiloé", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Queilén", province: "Chiloé", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Quellón", province: "Chiloé", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Quemchi", province: "Chiloé", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Quinchao", province: "Chiloé", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Osorno", province: "Osorno", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Puerto Octay", province: "Osorno", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Purranque", province: "Osorno", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Puyehue", province: "Osorno", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Río Negro", province: "Osorno", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "San Juan de la Costa", province: "Osorno", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "San Pablo", province: "Osorno", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Chaitén", province: "Palena", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Futaleufú", province: "Palena", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Hualaihué", province: "Palena", region_id: Region.find_by(name: "Región de los Lagos").id)
#Commune.create(name: "Coyhaique", province: "Coyhaique", region_id: Region.find_by(name: "Región de Aysén del General Carlos Ibáñez del Campo").id)
#Commune.create(name: "Lago Verde", province: "Coyhaique", region_id: Region.find_by(name: "Región de Aysén del General Carlos Ibáñez del Campo").id)
#Commune.create(name: "Aisén", province: "Aisén", region_id: Region.find_by(name: "Región de Aysén del General Carlos Ibáñez del Campo").id)
#Commune.create(name: "Cisnes", province: "Aisén", region_id: Region.find_by(name: "Región de Aysén del General Carlos Ibáñez del Campo").id)
#Commune.create(name: "Guaitecas", province: "Aisén", region_id: Region.find_by(name: "Región de Aysén del General Carlos Ibáñez del Campo").id)
#Commune.create(name: "Cochrane", province: "Capitán Pratt", region_id: Region.find_by(name: "Región de Aysén del General Carlos Ibáñez del Campo").id)
#Commune.create(name: "O’Higgins", province: "Capitán Pratt", region_id: Region.find_by(name: "Región de Aysén del General Carlos Ibáñez del Campo").id)
#Commune.create(name: "Tortel", province: "Capitán Pratt", region_id: Region.find_by(name: "Región de Aysén del General Carlos Ibáñez del Campo").id)
#Commune.create(name: "Chile Chico", province: "General Carrera", region_id: Region.find_by(name: "Región de Aysén del General Carlos Ibáñez del Campo").id)
#Commune.create(name: "Río Ibáñez", province: "General Carrera", region_id: Region.find_by(name: "Región de Aysén del General Carlos Ibáñez del Campo").id)
#Commune.create(name: "Punta Arenas", province: "Magallanes", region_id: Region.find_by(name: "Región de Magallanes y de la Antártica Chilena").id)
#Commune.create(name: "Laguna Blanca", province: "Magallanes", region_id: Region.find_by(name: "Región de Magallanes y de la Antártica Chilena").id)
#Commune.create(name: "Río Verde", province: "Magallanes", region_id: Region.find_by(name: "Región de Magallanes y de la Antártica Chilena").id)
#Commune.create(name: "San Gregorio", province: "Magallanes", region_id: Region.find_by(name: "Región de Magallanes y de la Antártica Chilena").id)
#Commune.create(name: "Cabo de Hornos", province: "Antártica Chilena", region_id: Region.find_by(name: "Región de Magallanes y de la Antártica Chilena").id)
#Commune.create(name: "Antártica", province: "Antártica Chilena", region_id: Region.find_by(name: "Región de Magallanes y de la Antártica Chilena").id)
#Commune.create(name: "Porvenir", province: "Tierra del Fuego", region_id: Region.find_by(name: "Región de Magallanes y de la Antártica Chilena").id)
#Commune.create(name: "Primavera", province: "Tierra del Fuego", region_id: Region.find_by(name: "Región de Magallanes y de la Antártica Chilena").id)
#Commune.create(name: "Timaukel", province: "Tierra del Fuego", region_id: Region.find_by(name: "Región de Magallanes y de la Antártica Chilena").id)
#Commune.create(name: "Natales", province: "Última Esperanza", region_id: Region.find_by(name: "Región de Magallanes y de la Antártica Chilena").id)
#Commune.create(name: "Torres del Paine", province: "Última Esperanza", region_id: Region.find_by(name: "Región de Magallanes y de la Antártica Chilena").id)
#Commune.create(name: "Santiago", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Cerrillos", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Cerro Navia", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Conchalí", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "El Bosque", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Estación Central", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Huechuraba", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Independencia", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "La Cisterna", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "La Florida", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "La Granja", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "La Pintana", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "La Reina", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Las Condes", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Lo Barnechea", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Lo Espejo", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Lo Prado", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Macul", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Maipú", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Ñuñoa", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Pedro Aguirre Cerda", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Peñalolén", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Providencia", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Pudahuel", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Quilicura", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Quinta Normal", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Recoleta", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Renca", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "San Joaquín", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "San Miguel", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "San Ramón", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Vitacura", province: "Santiago", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Puente Alto", province: "Cordillera", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Pirque", province: "Cordillera", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "San José de Maipo", province: "Cordillera", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Colina", province: "Chacabuco", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Lampa", province: "Chacabuco", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Tiltil", province: "Chacabuco", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "San Bernardo", province: "Maipo", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Buin", province: "Maipo", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Calera de Tango", province: "Maipo", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Paine", province: "Maipo", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Melipilla", province: "Mellipilla", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Alhué", province: "Mellipilla", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Curacaví", province: "Mellipilla", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "María Pinto", province: "Mellipilla", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "San Pedro", province: "Mellipilla", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Talagante", province: "Talagante", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "El Monte", province: "Talagante", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Isla de Maipo", province: "Talagante", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Padre Hurtado", province: "Talagante", region_id: Region.find_by(name: "Región Metropolitana").id)
#Commune.create(name: "Peñaflor", province: "Talagante", region_id: Region.find_by(name: "Región Metropolitana").id)